name: Workflow Record Input Example

on:
 workflow_dispatch:
    inputs:
      Record-ACAT:
        description: ‘Record ACAT-test run’
        required: true
        default:  $secrets.RECORD_OPTION = --record False
        type: choice
        options:
          - $secrets_RECORD_OPTION --record
          - $secrets_RECORD_OPTION --record false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Value is set to ${{ github.event.inputs.Record-ACAT.Value }} "