name: Workflow Record Input Example

on:
 workflow_dispatch:
    inputs:
      Record-ACAT:
        description: ‘Record ACAT-test run’
        required: true
        default: gh variable set { CYPRESS_RECORD_OPTION } = “--record”
        type: choice
        options:
          - gh variable set { CYPRESS_RECORD_OPTION } = “--record”
          - gh variable set { CYPRESS_RECORD_OPTION } = “--record false”
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Updating gh variable get" { CYPRESS_RECORD_OPTION }
             echo "Updated gh variable list" { CYPRESS_RECORD_OPTION }