name: Workflow Record Input Example

on:
 workflow_dispatch:
    inputs:
      Record-ACAT:
        description: ‘Record ACAT-test run’
        required: true
        default: --record false
        type: choice
        options:
          - --record false
          - --record 

 push:
    branches:
      - main
          
env:
  CYPRESS_RECORD_OPTION: ${{ github.event.inputs.Record-ACAT }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CYPRESS_RECORD_OPTION Value is set to ${{ github.event.inputs.Record-ACAT}}"

  notify:
    runs-on: ubuntu-latest
    if: (github.event.inputs.Record-ACAT == '--record')
    steps:
      - run: echo "CYPRESS_RECORD_OPTION set to ${{ github.event.inputs.Record-ACAT }} "
    env:
      CYPRESS_RECORD_OPTION: ${${{ vars.CYPRESS_RECORD_OPTION }}