name: Workflow Record Input Example

on:
 workflow_dispatch:
    inputs:
      Record-ACAT:
        description: ‘Record ACAT-test run’
        required: true
        default: --record false  
        type: choice
        options:
          - --record false
          - --record 

 push:
    branches:
      - main
          
env:
  CYPRESS_RECORD_OPTION: ${{ github.event.inputs.Record-ACAT || '--record false' }}
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Value is set to ${{ github.event.inputs.Record-ACAT}}