name: Workflow Record Input Example

on:
 workflow_dispatch:
    inputs:
      Record-ACAT:
        description: ‘Record ACAT-test run’
        required: true
        default:  $REC_OPTION = “--record false”
        type: choice
        options:
          - $REC_OPTION= "--record"
          - $RECORD_OPTION= “--record false”
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo " secret value $REC_OPTION"