name: Workflow Record Input Example

on:
 workflow_dispatch:
    inputs:
      Record-ACAT:
        description: ‘Record ACAT-test run’
        required: true
        default:  ${{ sectrets.RECORD_OPTION }} = “--record false”
        type: choice
        options:
          - ${{ secrets.RECORD_OPTION }} = "--record"
          - ${{ secrets.RECORD_OPTION }} = “--record false”
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret RECORD_OPTION value: ${{ secrets.RECORD_OPTION}} "